@bare_metal_port = 5128
@container_port = 5129
@rsa_HostAddress = http://localhost:{{container_port}}

POST {{rsa_HostAddress}}/rsa/factorization-request/
Content-Type: application/json

{
  "number": 11021,
  "lowerBound": 2,
  "upperBound": 20000
}
###

GET {{rsa_HostAddress}}/rsa/factorization-result?result=103
###
