# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameover.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameOver(object):
    def setupUi(self, GameOver):
        GameOver.setObjectName("GameOver")
        GameOver.resize(598, 433)
        self.centralwidget = QtWidgets.QWidget(GameOver)
        self.centralwidget.setObjectName("centralwidget")
        self.label_gameover = QtWidgets.QLabel(self.centralwidget)
        self.label_gameover.setGeometry(QtCore.QRect(140, 70, 341, 101))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_gameover.setFont(font)
        self.label_gameover.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_gameover.setObjectName("label_gameover")
        self.label_winner = QtWidgets.QLabel(self.centralwidget)
        self.label_winner.setGeometry(QtCore.QRect(210, 170, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_winner.setFont(font)
        self.label_winner.setObjectName("label_winner")
        self.label_score = QtWidgets.QLabel(self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(250, 240, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_score.setFont(font)
        self.label_score.setObjectName("label_score")
        self.label_black = QtWidgets.QLabel(self.centralwidget)
        self.label_black.setGeometry(QtCore.QRect(170, 290, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_black.setFont(font)
        self.label_black.setObjectName("label_black")
        self.label_black_score = QtWidgets.QLabel(self.centralwidget)
        self.label_black_score.setGeometry(QtCore.QRect(240, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_black_score.setFont(font)
        self.label_black_score.setObjectName("label_black_score")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 290, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_white_score = QtWidgets.QLabel(self.centralwidget)
        self.label_white_score.setGeometry(QtCore.QRect(310, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_white_score.setFont(font)
        self.label_white_score.setObjectName("label_white_score")
        self.label_white = QtWidgets.QLabel(self.centralwidget)
        self.label_white.setGeometry(QtCore.QRect(360, 290, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_white.setFont(font)
        self.label_white.setObjectName("label_white")
        self.pushButton_screen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_screen.setGeometry(QtCore.QRect(0, 0, 598, 433))
        self.pushButton_screen.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.pushButton_screen.setText("")
        self.pushButton_screen.setObjectName("pushButton_screen")
        GameOver.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GameOver)
        self.statusbar.setObjectName("statusbar")
        GameOver.setStatusBar(self.statusbar)

        self.retranslateUi(GameOver)
        QtCore.QMetaObject.connectSlotsByName(GameOver)

    def retranslateUi(self, GameOver):
        _translate = QtCore.QCoreApplication.translate
        GameOver.setWindowTitle(_translate("GameOver", "GameOver"))
        self.label_gameover.setText(_translate("GameOver", "Game Over"))
        self.label_winner.setText(_translate("GameOver", "Player wins!"))
        self.label_score.setText(_translate("GameOver", "Score"))
        self.label_black.setText(_translate("GameOver", "Black"))
        self.label_black_score.setText(_translate("GameOver", "32"))
        self.label.setText(_translate("GameOver", ":"))
        self.label_white_score.setText(_translate("GameOver", "32"))
        self.label_white.setText(_translate("GameOver", "White"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameOver = QtWidgets.QMainWindow()
    ui = Ui_GameOver()
    ui.setupUi(GameOver)
    GameOver.show()
    sys.exit(app.exec_())
