POST http://localhost:3002/create-jws
Content-Type: application/json

{
    "name": "Faruk",
    "email": "faruk@example.com"
}
###

POST http://localhost:3002/verify-jws
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmFydWsiLCJlbWFpbCI6ImZhcnVrQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg2Njk0NTE2fQ.3Nf3qqQ4oLUBqXAaZNMEWhTe_4knCM5uArZKt5GhhRg
###

POST http://localhost:3002/create-jwe
Content-Type: application/json

{
    "name": "Faruk",
    "email": "faruk@example.com"
}
###

POST http://localhost:3002/verify-jwe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWRQYXlsb2FkIjoiMTZhMTRkZTAwZWExNjhiMGQxZjE3MDA2NjIwYTEyNzcwZGQyZDRjNTRiNzA3OTJiOGQ1ZGQwMzJiOTY4M2E0OTEzZWNjYzllYzhkNjU5MTliYTQ4N2JhYWI0MzZhZTFkNjk1ZTM4ODZhOTcyMDBhN2Q1ZTRiZTM4YzYwMzIzNmEiLCJpYXQiOjE2ODY2OTQ1MzF9.OPImfSGTcSDl6HopvfXpc8Ui_NBspTuqBcabErjAo7Q
